server:
  port: 8222
spring:
  application:
    name: myMall-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
#zuul的动态路由配置
zuul:
  routes:
    myMall-user:
      path: /mymall-user  # 需要转发的路径
      serviceId: mymall-user # 最终转发的微服务（名称）
    myMall-web:
      path: /mymall-web  # 需要转发的路径
      serviceId: mymall-web # 最终转发的微服务（名称）
  SendErrorFilter:
    error:
      disable: true
